#!/bin/bash

# Update base packages
sudo apt update -y && sudo apt upgrade -y && sudo apt autoremove -y && sudo apt autoclean -y

# Add time and date to bash prompt
echo 'export PS1="-[\[$(tput sgr0)\]\[\033[38;5;10m\]\d\[$(tput sgr0)\]-\[$(tput sgr0)\]\[\033[38;5;10m\]\t\[$(tput sgr0)\]]-[\[$(tput sgr0)\]\[\033[38;5;214m\]\u\[$(tput sgr0)\]@\[$(tput sgr0)\]\[\033[38;5;196m\]\h\[$(tput sgr0)\]]-\n-[\[$(tput sgr0)\]\[\033[38;5;33m\]\w\[$(tput sgr0)\]]\\$ \[$(tput sgr0)\]"' >> .bashrc

# [OPTIONAL] Install zsh and add time / date to prompt
sudo apt install zsh -y
cd ~
echo 'PROMPT="[%n💀%m]:[%~]⮐"
RPROMPT="[%*]:[%W]"' >> ~.zshrc

# Install additional packages
sudo apt install tmux seclists

# Download auxillary tools and scripts from git
cd ~ && mkdir Potionstore && mkdir Potionstore/tools && cd Potionstore/Tools
# git clone https://github.com/mattmasel/HACKZORTOOLS
git clone https://github.com/carlospolop/privilege-escalation-awesome-scripts-suite.git
